/** 
 * Copyright 2004-2009 DTRules.com, Inc.
 *   
 * Licensed under the Apache License, Version 2.0 (the "License");  
 * you may not use this file except in compliance with the License.  
 * You may obtain a copy of the License at  
 *   
 *      http://www.apache.org/licenses/LICENSE-2.0  
 *   
 * Unless required by applicable law or agreed to in writing, software  
 * distributed under the License is distributed on an "AS IS" BASIS,  
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  
 * See the License for the specific language governing permissions and  
 * limitations under the License.  
 **/
 
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 19 01:22:42 EST 2010
//----------------------------------------------------

package com.dtrules.compiler.el.cup.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STARTS_WITH = 134;
  public static final int LBRACE = 74;
  public static final int ROPERATOR = 125;
  public static final int FLOAT = 53;
  public static final int GT = 59;
  public static final int INCLUDES = 66;
  public static final int GET = 57;
  public static final int UNDEFINED = 153;
  public static final int INCLUDE = 65;
  public static final int PLUSORMINUS = 107;
  public static final int VALUE = 156;
  public static final int THAN = 141;
  public static final int ARRAY_OF_VALUES = 10;
  public static final int RPAREN = 127;
  public static final int DEBUG = 33;
  public static final int RXMLVALUE = 130;
  public static final int ROUNDED = 126;
  public static final int DECREMENT = 35;
  public static final int LOCAL = 78;
  public static final int WHERE = 158;
  public static final int TIMES = 146;
  public static final int ATTRIBUTE = 13;
  public static final int SUM_OF = 138;
  public static final int FORALL = 55;
  public static final int RNULL = 124;
  public static final int ELSEIF = 45;
  public static final int UMINUS = 152;
  public static final int RBOOLEAN = 112;
  public static final int ARRAY = 9;
  public static final int EQ = 50;
  public static final int RINVALID = 121;
  public static final int DESCENDINGORDER = 37;
  public static final int YEAROF = 162;
  public static final int DAYS = 32;
  public static final int ADD = 4;
  public static final int WAS = 157;
  public static final int EACH = 41;
  public static final int WITHIN = 159;
  public static final int CONDITION = 26;
  public static final int ASSIGN = 12;
  public static final int MAPPINGKEY = 85;
  public static final int RNAME = 123;
  public static final int AFTER = 5;
  public static final int ONE = 101;
  public static final int EOF = 0;
  public static final int MINUS = 89;
  public static final int ONERROR = 102;
  public static final int CURRENT_TIMESTAMP = 29;
  public static final int RARRAY = 111;
  public static final int ALLOWING = 7;
  public static final int LTE = 83;
  public static final int MAP = 84;
  public static final int TRIM = 151;
  public static final int ACTION = 3;
  public static final int USING = 155;
  public static final int PERCENTOF = 104;
  public static final int ELSEIFNONEAREFOUND = 46;
  public static final int ELSE = 44;
  public static final int EQUAL = 51;
  public static final int HAVE = 62;
  public static final int END = 47;
  public static final int OR = 103;
  public static final int FIRST = 52;
  public static final int NAME = 92;
  public static final int INDEX_OF = 68;
  public static final int ON = 100;
  public static final int LESS = 77;
  public static final int QUESTIONMARK = 109;
  public static final int AND = 8;
  public static final int SUBTRACT = 137;
  public static final int DECIMAL_PLACES = 34;
  public static final int NUMBEROF = 98;
  public static final int THIS = 145;
  public static final int OF = 99;
  public static final int MATCHES = 87;
  public static final int TOBEREMOVED = 149;
  public static final int BY = 19;
  public static final int SEMI = 131;
  public static final int INCREMENT = 67;
  public static final int CHANGE = 20;
  public static final int TABLE = 139;
  public static final int BOOLEAN = 18;
  public static final int NEW = 95;
  public static final int THROUGH = 147;
  public static final int NO = 96;
  public static final int IDENT = 163;
  public static final int NEQ = 94;
  public static final int RCURLY = 114;
  public static final int ABSOLUTEVALUE = 2;
  public static final int AT = 14;
  public static final int BETWEEN = 16;
  public static final int RDATE = 115;
  public static final int PLUS = 106;
  public static final int LPAREN = 81;
  public static final int ALL = 6;
  public static final int RELATIONSHIP_BETWEEN = 118;
  public static final int CURRENT_DATE = 28;
  public static final int RBRACE = 113;
  public static final int RTABLE = 129;
  public static final int COPY = 27;
  public static final int GREATER = 58;
  public static final int RDECISIONTABLE = 116;
  public static final int ELEMENT = 43;
  public static final int CONTEXT = 24;
  public static final int COMMA = 25;
  public static final int HASA = 61;
  public static final int RLONG = 122;
  public static final int LT = 82;
  public static final int THENAME = 143;
  public static final int MONTHS = 90;
  public static final int ASCENDINGORDER = 11;
  public static final int MEMBER = 88;
  public static final int ISNULL = 72;
  public static final int DATE = 31;
  public static final int TOKENIZE = 150;
  public static final int NOT = 97;
  public static final int CVS = 30;
  public static final int DOES = 39;
  public static final int NAMEOF = 93;
  public static final int ENDIF = 48;
  public static final int BEFORE = 15;
  public static final int DEEPCOPY = 36;
  public static final int LONG = 79;
  public static final int FOR = 54;
  public static final int THEN = 142;
  public static final int INTEGER = 69;
  public static final int DIVIDE = 38;
  public static final int STRING = 135;
  public static final int DOUBLE = 40;
  public static final int EARLIEST = 42;
  public static final int TABLEINFORMATION = 140;
  public static final int LOWER_CASE = 80;
  public static final int ITS = 73;
  public static final int FROM = 56;
  public static final int ENTITY = 49;
  public static final int BOOL_FUNCTION = 17;
  public static final int WITH_BOUNDRY = 160;
  public static final int CLONE = 22;
  public static final int RANDOMIZE = 110;
  public static final int LENGTH = 76;
  public static final int POSSESSIVE = 108;
  public static final int GTE = 60;
  public static final int IS = 70;
  public static final int MULTIPLY = 91;
  public static final int UPPER_CASE = 154;
  public static final int IN = 64;
  public static final int error = 1;
  public static final int YEARS = 161;
  public static final int SORT = 133;
  public static final int IF = 63;
  public static final int RDOUBLE = 117;
  public static final int RSTRING = 128;
  public static final int ISNOTNULL = 71;
  public static final int COLON = 23;
  public static final int SET = 132;
  public static final int PERFORM = 105;
  public static final int SUBSTRING = 136;
  public static final int LCURLY = 75;
  public static final int THERE = 144;
  public static final int CLEAR = 21;
  public static final int REMOVE = 119;
  public static final int RENTITY = 120;
  public static final int TO = 148;
  public static final int MATCH = 86;
}

