// Copyright 2024 Paul Snow
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

const docDatabase = `KV Database Design for DTRules
================================

This topic covers how to design a key-value store whose schema is driven by
an EDD (Entity Data Dictionary). It is targeted at consumers who need to
persist DTRules entities — for example, to store tax-return state between
API calls or to build a rules-driven microservice with a Redis or DynamoDB
back-end.

The guidance here is grounded in how DTRules internally models entities: an
REntity is a named, ID-stamped typed dictionary whose attribute set is fixed
at load time by the EDD. Everything below derives from that model.


Overview: EDD as Schema
-----------------------
The EDD declares every entity and every attribute that can exist in a session.
Think of each <entity> as a table definition and each <field> as a column.
When you persist a session to a KV store, you are essentially serializing
those tables into a flat key space.

Given:

    <entity name="taxpayer">
        <field name="ssn"            type="string"  default_value=""/>
        <field name="filing_status"  type="string"  default_value="single"/>
        <field name="agi"            type="double"  default_value="0.0"/>
        <field name="dependents"     type="array"   subtype="dependent"/>
    </entity>

    <entity name="dependent">
        <field name="name"           type="string"  default_value=""/>
        <field name="relationship"   type="string"  default_value=""/>
        <field name="dob"            type="date"/>
    </entity>

...the KV schema design follows directly. Each section below covers one
design concern.


Key Composition
---------------
DTRules identifies an entity instance by two things: its type name and its
runtime integer ID. The recommended key scheme is:

    <entity>:<id>:<attribute>

Examples:

    taxpayer:42:ssn
    taxpayer:42:filing_status
    taxpayer:42:agi
    dependent:7:name
    dependent:7:dob

Use colon delimiters. Slash-delimited keys (taxpayer/42/agi) also work, but
colons are the conventional separator for Redis, and most KV stores treat
slashes as path separators, which can cause confusion with scan operations.

Collision modes to watch for:
- Entity names that contain colons are not valid EDD names, so there is no
  collision between the separator and an entity name.
- Integer IDs are generated by the session and are unique within a session.
  If you persist multiple sessions to the same KV namespace, add a session
  prefix: <session>:<entity>:<id>:<attribute>.
- The EDD-reserved attribute "mapping*key" contains an asterisk — store it
  as-is in the key path: taxpayer:42:mapping*key.


Built-in Attributes: mapping*key and self-reference
-----------------------------------------------------
Every entity in DTRules has two implicit attributes added at creation time:

1. <entity-name> (self-reference): points back to the entity itself.
   Do not persist this — it is a runtime identity, not data.

2. mapping*key (string): the external identifier set by the data loader
   when it creates an entity from XML or JSON input. This is the value
   from the ID field in the mapping configuration (e.g., the "ssn" field
   for a taxpayer, or the "id" field for a dependent).

   mapping*key is the bridge between your external data store and the
   DTRules runtime. Persist it:

       PUT taxpayer:42:mapping*key  -> "123-45-6789"
       PUT dependent:7:mapping*key  -> "dep-001"

   On reload, set mapping*key first so that any decision tables that read
   "mapping key" in EL get the correct value.

   In EL:
       mapping key    -> returns current entity's mapping*key as a string


Arrays
------
Arrays in the EDD have a subtype that identifies the element type. Two
storage schemes work well; pick one and apply it consistently.

Scheme A — length-prefixed enumerated keys (recommended):

    PUT taxpayer:42:dependents:count  -> 2
    PUT taxpayer:42:dependents:0      -> 7    (dependent ID)
    PUT taxpayer:42:dependents:1      -> 11   (dependent ID)

    GET taxpayer:42:dependents:count  -> read length
    GET taxpayer:42:dependents:0..N   -> read each element

Scheme B — JSON serialization of the ID list:

    PUT taxpayer:42:dependents  -> "[7, 11]"

Scheme A is preferable when:
- Elements are added or removed frequently (no deserialization cost).
- You want to scan a subset without fetching the whole array.
- The array can be large.

Scheme B is preferable when:
- The array is always read as a whole and never partially modified.
- Simplicity matters more than update efficiency.

For scalar arrays (array of integer, array of string), store values directly
rather than IDs:

    PUT taxpayer:42:prior_year_states:count  -> 3
    PUT taxpayer:42:prior_year_states:0      -> "CO"
    PUT taxpayer:42:prior_year_states:1      -> "CA"
    PUT taxpayer:42:prior_year_states:2      -> "TX"


References
----------
When an entity field has type="entity" and a subtype, it holds a reference
to another entity instance. Persist the referenced entity's ID:

    <entity name="job">
        <field name="taxpayer"  type="entity" subtype="taxpayer"/>
        <field name="wages"     type="double" default_value="0.0"/>
    </entity>

    PUT job:3:taxpayer  -> 42     (taxpayer ID)
    PUT job:3:wages     -> 85000.0

On read, load the referenced entity separately:

    GET job:3:taxpayer  -> 42
    GET taxpayer:42:*   -> (load all taxpayer:42 attributes)

Circular references (entity A references entity B which references A) are
resolved by loading lazily: load the IDs first, then materialize entities
as needed. The EDD self-reference attribute does not introduce a real cycle
because it is not persisted.


mapping*key and KV Lookups
---------------------------
mapping*key enables a second lookup path. In addition to the numeric ID key,
you can maintain a secondary index:

    PUT taxpayer:by-ssn:123-45-6789  -> 42   (maps SSN to runtime ID)

This lets you look up a taxpayer by SSN (the business key) and then load
all attributes by the runtime ID. The data loader sets mapping*key
automatically from the configured ID field in the mapping XML.

In EL, "mapping key" returns the string value of the current entity's
mapping*key attribute. Decision tables can use this to build lookup keys
or to emit debug output:

    debug "loading taxpayer " + mapping key


Worked Example: job, taxpayer, dependent
-----------------------------------------
EDD fragment:

    <entity name="job">
        <field name="id"         type="integer" default_value="0"/>
        <field name="taxpayer"   type="entity"  subtype="taxpayer"/>
        <field name="dependents" type="array"   subtype="dependent"/>
        <field name="wages"      type="double"  default_value="0.0"/>
    </entity>

    <entity name="taxpayer">
        <field name="ssn"           type="string"  default_value=""/>
        <field name="filing_status" type="string"  default_value="single"/>
        <field name="agi"           type="double"  default_value="0.0"/>
    </entity>

    <entity name="dependent">
        <field name="name"         type="string"  default_value=""/>
        <field name="relationship" type="string"  default_value="child"/>
        <field name="dob"          type="date"/>
    </entity>

A session with one job (ID 3), one taxpayer (ID 42), and two dependents
(IDs 7 and 11) serializes to:

    PUT job:3:mapping*key        -> "job-2024"
    PUT job:3:id                 -> 3
    PUT job:3:taxpayer           -> 42
    PUT job:3:dependents:count   -> 2
    PUT job:3:dependents:0       -> 7
    PUT job:3:dependents:1       -> 11
    PUT job:3:wages              -> 85000.0

    PUT taxpayer:42:mapping*key   -> "123-45-6789"
    PUT taxpayer:42:ssn           -> "123-45-6789"
    PUT taxpayer:42:filing_status -> "MFJ"
    PUT taxpayer:42:agi           -> 85000.0

    PUT dependent:7:mapping*key   -> "dep-001"
    PUT dependent:7:name          -> "Alice"
    PUT dependent:7:relationship  -> "child"
    PUT dependent:7:dob           -> "2012-03-15"

    PUT dependent:11:mapping*key  -> "dep-002"
    PUT dependent:11:name         -> "Bob"
    PUT dependent:11:relationship -> "child"
    PUT dependent:11:dob          -> "2015-07-22"

Loading back into a DTRules session:

    // 1. Enumerate all entity IDs by type
    ids := SCAN "taxpayer:*:mapping*key"
    // -> ["taxpayer:42:mapping*key"]

    // 2. Load each entity's attributes
    for each id in ids:
        numericID = parse(id)  // 42
        attrs = SCAN "taxpayer:<numericID>:*"
        session.CreateEntity("taxpayer", numericID)
        for each attr in attrs:
            session.SetAttribute("taxpayer", numericID, attr.name, attr.value)

    // 3. Resolve references after all entities exist
    taxpayerID = GET "job:3:taxpayer"   // 42
    session.SetAttribute("job", 3, "taxpayer", session.GetEntity("taxpayer", 42))

    // 4. Rebuild arrays
    count = GET "job:3:dependents:count"   // 2
    for i = 0 to count-1:
        depID = GET "job:3:dependents:<i>"
        session.AppendToArray("job", 3, "dependents", session.GetEntity("dependent", depID))


Migration: EDD Changes
-----------------------
When the EDD changes, existing KV data may become inconsistent. Handle each
change type as follows:

New attribute (field added to entity):
    New attribute has a default_value in the EDD. Existing rows in the KV
    store simply lack the key. On read, detect the missing key and return
    the EDD default. No rewrite is needed until the attribute is written.

Removed attribute (field deleted from entity):
    The key is orphaned. Old data remains in the store but the runtime
    will not read it. Safe to ignore, or run a one-time cleanup:
        DELETE all keys matching <entity>:*:<removed-attr>

Renamed attribute:
    There is no EDD-level rename concept; a rename is a delete + add. Run
    a one-time rewrite:
        for each key matching <entity>:*:<old-attr>:
            PUT <entity>:<id>:<new-attr>  -> GET <entity>:<id>:<old-attr>
            DELETE <entity>:<id>:<old-attr>

Type change (e.g., integer -> double):
    Values stored as strings survive most type changes. Verify conversion
    before migrating: read all values, convert, write back, test.

Entity renamed:
    All keys for the old entity name must be rewritten to the new name.
    This is the most disruptive change — avoid renaming entities in
    production schemas.

Entity added:
    No migration needed. New entities have no stored data yet.

Entity removed:
    Orphaned data remains. Run a one-time cleanup:
        DELETE all keys matching <removed-entity>:*


Scanning and Enumeration
------------------------
To enumerate all instances of an entity type, scan by prefix:

    SCAN "taxpayer:*"            -> all taxpayer keys
    SCAN "taxpayer:42:*"         -> all attributes of taxpayer 42
    SCAN "taxpayer:*:ssn"        -> ssn attribute across all taxpayers

Redis SCAN with MATCH, DynamoDB begins_with, or a sorted set of IDs all
support this pattern. If your KV store does not support prefix scans,
maintain a separate set per entity type:

    SADD "taxpayer:ids"  42
    SADD "dependent:ids" 7
    SADD "dependent:ids" 11

This gives you O(1) enumeration at the cost of an extra write per entity
creation.


See Also
--------
  dtrules docs edd         Entity Data Dictionary field types and defaults
  dtrules docs xml-format  EDD XML structure
  dtrules docs el          mapping key in EL expressions
`
