// Copyright 2024 Paul Snow
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// excel2dt imports decision tables from Excel files and generates XML.
//
// Usage:
//
//	excel2dt -input excel/ -output xml/TaxReturn_dt.xml
//	excel2dt -input single_table.xlsx -output xml/SingleTable_dt.xml
//
// The tool can import from:
//   - A directory containing multiple .xlsx files
//   - A single .xlsx file
//
// The tool supports two Excel formats:
//   - dt2excel format: Generated by the dt2excel tool
//   - exporter format: Generated by the DTRules Excel exporter
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/DTRules/DTRules/go/pkg/dtrules/excel"
)

func main() {
	inputPath := flag.String("input", "", "Input Excel file or directory")
	outputFile := flag.String("output", "", "Output XML file path")
	verbose := flag.Bool("v", false, "Verbose output")
	sort := flag.Bool("sort", true, "Sort tables by TABLE_NUMBER")

	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "excel2dt - Import decision tables from Excel to XML\n\n")
		fmt.Fprintf(os.Stderr, "Usage:\n")
		fmt.Fprintf(os.Stderr, "  excel2dt -input <excel_dir> -output <output.xml>\n")
		fmt.Fprintf(os.Stderr, "  excel2dt -input <file.xlsx> -output <output.xml>\n\n")
		fmt.Fprintf(os.Stderr, "Examples:\n")
		fmt.Fprintf(os.Stderr, "  excel2dt -input excel/ -output xml/TaxReturn_dt.xml\n")
		fmt.Fprintf(os.Stderr, "  excel2dt -input tables.xlsx -output xml/Tables_dt.xml -v\n\n")
		fmt.Fprintf(os.Stderr, "Options:\n")
		flag.PrintDefaults()
	}

	flag.Parse()

	if *inputPath == "" {
		fmt.Fprintln(os.Stderr, "Error: -input is required")
		flag.Usage()
		os.Exit(1)
	}

	if *outputFile == "" {
		fmt.Fprintln(os.Stderr, "Error: -output is required")
		flag.Usage()
		os.Exit(1)
	}

	importer := excel.NewDTImporter()
	importer.SetVerbose(*verbose)

	// Check if input is a file or directory
	info, err := os.Stat(*inputPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: cannot access input path: %v\n", err)
		os.Exit(1)
	}

	var tables *excel.DecisionTablesXML

	if info.IsDir() {
		if *verbose {
			fmt.Printf("Importing from directory: %s\n", *inputPath)
		}
		tables, err = importer.ImportDecisionTablesFromDir(*inputPath)
	} else {
		if !strings.HasSuffix(strings.ToLower(*inputPath), ".xlsx") {
			fmt.Fprintln(os.Stderr, "Error: input file must be .xlsx")
			os.Exit(1)
		}
		if *verbose {
			fmt.Printf("Importing from file: %s\n", *inputPath)
		}
		tables, err = importer.ImportDecisionTables(*inputPath)
	}

	if err != nil {
		fmt.Fprintf(os.Stderr, "Error importing: %v\n", err)
		os.Exit(1)
	}

	if len(tables.Tables) == 0 {
		fmt.Fprintln(os.Stderr, "Warning: no decision tables found")
	}

	// Sort tables by number if requested
	if *sort {
		excel.SortTablesByNumber(tables)
	}

	// Create output directory if needed
	outDir := filepath.Dir(*outputFile)
	if outDir != "." && outDir != "" {
		if err := os.MkdirAll(outDir, 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error creating output directory: %v\n", err)
			os.Exit(1)
		}
	}

	// Write XML output
	if err := importer.WriteXML(tables, *outputFile); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing XML: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Successfully imported %d decision tables to %s\n", len(tables.Tables), *outputFile)
}
