/** 
 * Copyright 2004-2009 DTRules.com, Inc.
 *   
 * Licensed under the Apache License, Version 2.0 (the "License");  
 * you may not use this file except in compliance with the License.  
 * You may obtain a copy of the License at  
 *   
 *      http://www.apache.org/licenses/LICENSE-2.0  
 *   
 * Unless required by applicable law or agreed to in writing, software  
 * distributed under the License is distributed on an "AS IS" BASIS,  
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  
 * See the License for the specific language governing permissions and  
 * limitations under the License.  
 **/
 
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Oct 22 00:36:01 CDT 2011
//----------------------------------------------------

package com.dtrules.compiler.ebl.cup.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STARTS_WITH = 139;
  public static final int LBRACE = 76;
  public static final int ROPERATOR = 130;
  public static final int FLOAT = 54;
  public static final int GT = 60;
  public static final int INCLUDES = 67;
  public static final int GET = 59;
  public static final int UNDEFINED = 157;
  public static final int INCLUDE = 66;
  public static final int PLUSORMINUS = 109;
  public static final int VALUE = 160;
  public static final int POLICYSTATEMENT = 110;
  public static final int ARRAY_OF_VALUES = 10;
  public static final int RPAREN = 132;
  public static final int DEBUG = 32;
  public static final int RXMLVALUE = 135;
  public static final int ROUNDED = 131;
  public static final int DECREMENT = 34;
  public static final int LOCAL = 79;
  public static final int WHERE = 162;
  public static final int TIMES = 150;
  public static final int ATTRIBUTE = 13;
  public static final int SUM_OF = 143;
  public static final int FORALL = 56;
  public static final int RNULL = 129;
  public static final int ELSEIF = 44;
  public static final int UMINUS = 156;
  public static final int RBOOLEAN = 117;
  public static final int ARRAY = 9;
  public static final int EQ = 50;
  public static final int RINVALID = 126;
  public static final int DESCENDINGORDER = 36;
  public static final int YEAROF = 166;
  public static final int DAYS = 31;
  public static final int ADD = 4;
  public static final int WAS = 161;
  public static final int EACH = 40;
  public static final int WITHIN = 163;
  public static final int CONDITION = 26;
  public static final int ASSIGN = 12;
  public static final int MAPPINGKEY = 86;
  public static final int RNAME = 128;
  public static final int AFTER = 5;
  public static final int ONE = 103;
  public static final int EOF = 0;
  public static final int MINUS = 90;
  public static final int ONERROR = 104;
  public static final int CURRENT_TIMESTAMP = 29;
  public static final int RARRAY = 116;
  public static final int ALLOWING = 7;
  public static final int LTE = 84;
  public static final int MAP = 85;
  public static final int TRIM = 155;
  public static final int ACTION = 3;
  public static final int USING = 159;
  public static final int PERCENTOF = 106;
  public static final int ELSEIFNONEAREFOUND = 45;
  public static final int ELSE = 43;
  public static final int HAVE = 63;
  public static final int END = 46;
  public static final int ISWITHIN = 74;
  public static final int OR = 105;
  public static final int FIRST = 53;
  public static final int NAME = 93;
  public static final int INDEX_OF = 69;
  public static final int ON = 102;
  public static final int QUESTIONMARK = 114;
  public static final int AND = 8;
  public static final int SUBTRACT = 142;
  public static final int DECIMAL_PLACES = 33;
  public static final int NUMBEROF = 100;
  public static final int THIS = 149;
  public static final int OF = 101;
  public static final int MATCHES = 88;
  public static final int TOBEREMOVED = 153;
  public static final int BY = 19;
  public static final int SEMI = 136;
  public static final int INCREMENT = 68;
  public static final int CHANGE = 20;
  public static final int TABLE = 144;
  public static final int BOOLEAN = 18;
  public static final int NEW = 97;
  public static final int THROUGH = 151;
  public static final int NO = 98;
  public static final int IDENT = 167;
  public static final int NEQ = 95;
  public static final int RCURLY = 119;
  public static final int ABSOLUTEVALUE = 2;
  public static final int PRINT = 113;
  public static final int FIND = 52;
  public static final int AT = 14;
  public static final int BETWEEN = 16;
  public static final int RDATE = 120;
  public static final int PLUS = 108;
  public static final int LPAREN = 82;
  public static final int EQ_IGNORE_CASE = 51;
  public static final int ALL = 6;
  public static final int RELATIONSHIP_BETWEEN = 123;
  public static final int CURRENT_DATE = 28;
  public static final int RBRACE = 118;
  public static final int RTABLE = 134;
  public static final int COPY = 27;
  public static final int RDECISIONTABLE = 121;
  public static final int ELEMENT = 42;
  public static final int CONTEXT = 24;
  public static final int COMMA = 25;
  public static final int HASA = 62;
  public static final int RLONG = 127;
  public static final int LT = 83;
  public static final int THENAME = 147;
  public static final int MONTHS = 91;
  public static final int ASCENDINGORDER = 11;
  public static final int MEMBER = 89;
  public static final int ISNULL = 73;
  public static final int DATE = 30;
  public static final int TOKENIZE = 154;
  public static final int NOT = 99;
  public static final int DOES = 38;
  public static final int NAMEOF = 94;
  public static final int POLICYSTATEMENTS = 111;
  public static final int ENDIF = 48;
  public static final int BEFORE = 15;
  public static final int DEEPCOPY = 35;
  public static final int LONG = 80;
  public static final int FOR = 55;
  public static final int THEN = 146;
  public static final int INTEGER = 70;
  public static final int DIVIDE = 37;
  public static final int STRING = 140;
  public static final int DOUBLE = 39;
  public static final int EARLIEST = 41;
  public static final int TABLEINFORMATION = 145;
  public static final int LOWER_CASE = 81;
  public static final int ITS = 75;
  public static final int FROM = 58;
  public static final int ENTITY = 49;
  public static final int BOOL_FUNCTION = 17;
  public static final int NEQ_IGNORE_CASE = 96;
  public static final int WITH_BOUNDRY = 164;
  public static final int CLONE = 22;
  public static final int RANDOMIZE = 115;
  public static final int LENGTH = 78;
  public static final int POSSESSIVE = 112;
  public static final int GTE = 61;
  public static final int FOREACH = 57;
  public static final int IS = 71;
  public static final int MULTIPLY = 92;
  public static final int UPPER_CASE = 158;
  public static final int IN = 65;
  public static final int error = 1;
  public static final int YEARS = 165;
  public static final int SORT = 138;
  public static final int IF = 64;
  public static final int RDOUBLE = 122;
  public static final int RSTRING = 133;
  public static final int ISNOTNULL = 72;
  public static final int COLON = 23;
  public static final int SET = 137;
  public static final int PERFORM = 107;
  public static final int SUBSTRING = 141;
  public static final int LCURLY = 77;
  public static final int THERE = 148;
  public static final int CLEAR = 21;
  public static final int REMOVE = 124;
  public static final int ENDFF = 47;
  public static final int RENTITY = 125;
  public static final int TO = 152;
  public static final int MATCH = 87;
}

