/** 
 * Copyright 2004-2009 DTRules.com, Inc.
 *   
 * Licensed under the Apache License, Version 2.0 (the "License");  
 * you may not use this file except in compliance with the License.  
 * You may obtain a copy of the License at  
 *   
 *      http://www.apache.org/licenses/LICENSE-2.0  
 *   
 * Unless required by applicable law or agreed to in writing, software  
 * distributed under the License is distributed on an "AS IS" BASIS,  
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  
 * See the License for the specific language governing permissions and  
 * limitations under the License.  
 **/
 
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 10 01:55:50 EST 2011
//----------------------------------------------------

package com.dtrules.compiler.el.cup.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STARTS_WITH = 131;
  public static final int LBRACE = 72;
  public static final int ROPERATOR = 122;
  public static final int FLOAT = 52;
  public static final int GT = 57;
  public static final int INCLUDES = 64;
  public static final int GET = 56;
  public static final int UNDEFINED = 149;
  public static final int INCLUDE = 63;
  public static final int PLUSORMINUS = 104;
  public static final int VALUE = 152;
  public static final int ARRAY_OF_VALUES = 10;
  public static final int RPAREN = 124;
  public static final int DEBUG = 33;
  public static final int RXMLVALUE = 127;
  public static final int ROUNDED = 123;
  public static final int DECREMENT = 35;
  public static final int LOCAL = 75;
  public static final int WHERE = 154;
  public static final int TIMES = 142;
  public static final int ATTRIBUTE = 13;
  public static final int SUM_OF = 135;
  public static final int FORALL = 54;
  public static final int RNULL = 121;
  public static final int ELSEIF = 45;
  public static final int UMINUS = 148;
  public static final int RBOOLEAN = 109;
  public static final int ARRAY = 9;
  public static final int EQ = 50;
  public static final int RINVALID = 118;
  public static final int DESCENDINGORDER = 37;
  public static final int YEAROF = 158;
  public static final int DAYS = 32;
  public static final int ADD = 4;
  public static final int WAS = 153;
  public static final int EACH = 41;
  public static final int WITHIN = 155;
  public static final int CONDITION = 26;
  public static final int ASSIGN = 12;
  public static final int MAPPINGKEY = 82;
  public static final int RNAME = 120;
  public static final int AFTER = 5;
  public static final int ONE = 98;
  public static final int EOF = 0;
  public static final int MINUS = 86;
  public static final int ONERROR = 99;
  public static final int CURRENT_TIMESTAMP = 29;
  public static final int RARRAY = 108;
  public static final int ALLOWING = 7;
  public static final int LTE = 80;
  public static final int MAP = 81;
  public static final int TRIM = 147;
  public static final int ACTION = 3;
  public static final int USING = 151;
  public static final int PERCENTOF = 101;
  public static final int ELSEIFNONEAREFOUND = 46;
  public static final int ELSE = 44;
  public static final int HAVE = 60;
  public static final int END = 47;
  public static final int OR = 100;
  public static final int FIRST = 51;
  public static final int NAME = 89;
  public static final int INDEX_OF = 66;
  public static final int ON = 97;
  public static final int QUESTIONMARK = 106;
  public static final int AND = 8;
  public static final int SUBTRACT = 134;
  public static final int DECIMAL_PLACES = 34;
  public static final int NUMBEROF = 95;
  public static final int THIS = 141;
  public static final int OF = 96;
  public static final int MATCHES = 84;
  public static final int TOBEREMOVED = 145;
  public static final int BY = 19;
  public static final int SEMI = 128;
  public static final int INCREMENT = 65;
  public static final int CHANGE = 20;
  public static final int TABLE = 136;
  public static final int BOOLEAN = 18;
  public static final int NEW = 92;
  public static final int THROUGH = 143;
  public static final int NO = 93;
  public static final int IDENT = 159;
  public static final int NEQ = 91;
  public static final int RCURLY = 111;
  public static final int ABSOLUTEVALUE = 2;
  public static final int AT = 14;
  public static final int BETWEEN = 16;
  public static final int RDATE = 112;
  public static final int PLUS = 103;
  public static final int LPAREN = 78;
  public static final int ALL = 6;
  public static final int RELATIONSHIP_BETWEEN = 115;
  public static final int CURRENT_DATE = 28;
  public static final int RBRACE = 110;
  public static final int RTABLE = 126;
  public static final int COPY = 27;
  public static final int RDECISIONTABLE = 113;
  public static final int ELEMENT = 43;
  public static final int CONTEXT = 24;
  public static final int COMMA = 25;
  public static final int HASA = 59;
  public static final int RLONG = 119;
  public static final int LT = 79;
  public static final int THENAME = 139;
  public static final int MONTHS = 87;
  public static final int ASCENDINGORDER = 11;
  public static final int MEMBER = 85;
  public static final int ISNULL = 70;
  public static final int DATE = 31;
  public static final int TOKENIZE = 146;
  public static final int NOT = 94;
  public static final int CVS = 30;
  public static final int DOES = 39;
  public static final int NAMEOF = 90;
  public static final int ENDIF = 48;
  public static final int BEFORE = 15;
  public static final int DEEPCOPY = 36;
  public static final int LONG = 76;
  public static final int FOR = 53;
  public static final int THEN = 138;
  public static final int INTEGER = 67;
  public static final int DIVIDE = 38;
  public static final int STRING = 132;
  public static final int DOUBLE = 40;
  public static final int EARLIEST = 42;
  public static final int TABLEINFORMATION = 137;
  public static final int LOWER_CASE = 77;
  public static final int ITS = 71;
  public static final int FROM = 55;
  public static final int ENTITY = 49;
  public static final int BOOL_FUNCTION = 17;
  public static final int WITH_BOUNDRY = 156;
  public static final int CLONE = 22;
  public static final int RANDOMIZE = 107;
  public static final int LENGTH = 74;
  public static final int POSSESSIVE = 105;
  public static final int GTE = 58;
  public static final int IS = 68;
  public static final int MULTIPLY = 88;
  public static final int UPPER_CASE = 150;
  public static final int IN = 62;
  public static final int error = 1;
  public static final int YEARS = 157;
  public static final int SORT = 130;
  public static final int IF = 61;
  public static final int RDOUBLE = 114;
  public static final int RSTRING = 125;
  public static final int ISNOTNULL = 69;
  public static final int COLON = 23;
  public static final int SET = 129;
  public static final int PERFORM = 102;
  public static final int SUBSTRING = 133;
  public static final int LCURLY = 73;
  public static final int THERE = 140;
  public static final int CLEAR = 21;
  public static final int REMOVE = 116;
  public static final int RENTITY = 117;
  public static final int TO = 144;
  public static final int MATCH = 83;
}

